"""empty message

Revision ID: 2062a4ee3c81
Revises: db69b9b019a0
Create Date: 2024-09-07 11:36:52.337327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2062a4ee3c81'
down_revision = 'db69b9b019a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
